# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs: "0.8"
    - nodejs: "0.10"
    - nodejs: "0.12"
    - nodejs: "3"
    - nodejs: "4"
    - nodejs: "5"

install:
  # openssl
  - appveyor DownloadFile http://slproweb.com/download/Win32OpenSSL-1_0_2d.exe
  - Win32OpenSSL-1_0_2d.exe /silent /verysilent /sp- /suppressmsgboxes
  # node
  - ps: Install-Product node $env:nodejs
  - IF %nodejs% EQU 0.8 npm -g install npm
  - IF %nodejs% EQU 0.8 set PATH=%APPDATA%\npm;%PATH%
  # forsake
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
version: "{build}"
